[package]
name = "easyparcli"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
clap = { version="4.*", features = ["derive"] }
anyhow = "*"
tokio = { version = "1.*", features = ["full"]}
async-channel = "1.*"
